base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^proceed_ticket/(?P<ticket_id>\d+)/(?P<next_state_id>\d+)/$',
        views.proceed_ticket, name='proceed_ticket')
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

danadams_shop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from raw_materials_dept.admin import admin_site

urlpatterns = [
    url(r'^raw_dept_admin/', admin_site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'', include('inventory.urls', namespace='inventory')),
    url(r'^raw_materials_dept/', include('raw_materials_dept.urls', namespace='raw_materials_dept')),
    url(r'^base/', include('base.urls', namespace='base')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.conf.urls import url

from inventory import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]
from django import apps

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class AddProductForms(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddProductForms
from .cart import Cart
from inventory.models import Product
# from coupons.forms import CouponForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForms(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = AddProductForms(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    # coupon_form = CouponForm()
    return render(request, 'cart/detail.html', {'cart': cart}),
                                                # 'coupon_form': coupon_form})

cart/templates/cart/detail.html
{% extends "inventory/base3.html" %}
{% load static %}
{% block title %}Your Shopping Cart{% endblock %}
{% block otherLinks %}{% endblock %}
{% block container %}

<!--start-ckeckout-->
	<div class="ckeckout">
		<div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="ckeck-top heading">
				<h1>YOUR SHOPPING CART</h1>
                        </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="ckeckout-top">
			<div class="cart-items">
            {% with total_items=cart|length %}
                <h3 class="cartheader">My Shopping Bag ({{ total_items }} item{{ total_items|pluralize }})</h3>
            {% endwith %}
				<script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});
					});
			   </script>
			<script>$(document).ready(function(c) {
					$('.close2').on('click', function(c){
						$('.cart-header1').fadeOut('slow', function(c){
							$('.cart-header1').remove();
						});
						});
					});
			   </script>
			   <script>$(document).ready(function(c) {
					$('.close3').on('click', function(c){
						$('.cart-header2').fadeOut('slow', function(c){
							$('.cart-header2').remove();
						});
						});
					});
			   </script>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                <td class="num">GH₵{{ item.price }}</td>
                <td class="num">GH₵{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">GH₵{{ cart.get_total_price }}</td>
            </tr>
            <tr>
                <td>
                    "{{ cart.coupon.code }}" coupon
                    ({{ cart.coupon.discount }}% off)
                </td>
                <td colspan="4"></td>
                <td class="num neg">- GH₵{{ cart.get_discount|floatformat:"2" }}</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">GH₵{{ cart.get_total_price_after_discount|floatformat:"2" }}</td>
        </tr>

        </tbody>
    </table>
            <p>Apply a coupon:</p>
            <form action="{% url "coupons:coupon_apply" %}" method="post">
                {{ coupon_form }}
                <input type="submit" value="Apply">
                {% csrf_token %}
            </form>

		 </div>
		</div>
                </div>
            </div>
        <div class="row">
            <div class="col-sm-12">
                <p class="text-right">
                <a href="{% url "inventory:product_list" %}" class="button light">Continue shopping</a>
                <a href="{% url "orders:order_create" %}" class="button">Checkout</a>
            </p>
            </div>
        </div>


	</div>
    </div>
	<!--end-ckeckout-->
{% endblock %}