base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^proceed_ticket/(?P<ticket_id>\d+)/(?P<next_state_id>\d+)/$',
        views.proceed_ticket, name='proceed_ticket')
]

danadams_shop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from raw_materials_dept.admin import admin_site

urlpatterns = [
    url(r'^raw_dept_admin/', admin_site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'', include('inventory.urls', namespace='inventory')),
    url(r'^raw_materials_dept/', include('raw_materials_dept.urls', namespace='raw_materials_dept')),
    url(r'^base/', include('base.urls', namespace='base')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.conf.urls import url

urlpatterns = [

]

staff/models.py
from django.db import models
from django.utils.translation import ugettext_lazy
from .managers import TemporalQuerySet
# Create your models here.


class Employee(models.Model):
    emp_num = models.IntegerField(primary_key=True)
    birth_date = models.DateField()
    first_name = models.CharField(max_length=14)
    last_name = models.CharField(max_length=16)
    gender = models.CharField(max_length=1)
    hire_date = models.DateField()

    class Meta:
        db_table = 'staff'

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class Department(models.Model):
    """Danadams Department Model"""
    dept_name = models.CharField(max_length=50, unique=True)
    dept_num = models.CharField(max_length=10, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'departments'
        ordering = ('dept_num',)

    def __str__(self):
        return self.dept_name


class DepartmentStaff(models.Model):
    """Model of staff in each department"""
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, db_column='emp_num')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_num')
    from_date = models.DateField()
    to_date = models.DateField()

    class Meta:
        db_table = 'employees'
        verbose_name_plural = 'Department Staff'

    def __str__(self):
        return '{0}'.format(self.employee.first_name)


class DepartmentManager(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_num')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_num')
    from_date = models.DateField()
    to_date = models.DateField()

    objects = TemporalQuerySet.as_manager()

    class Meta:
        db_table = 'dept_manager'
        ordering = ['-from_date']
        verbose_name_plural = 'Department Managers'


class Salary(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_num')
    salary = models.IntegerField()
    from_date = models.DateField()
    to_date = models.DateField()

    objects = TemporalQuerySet.as_manager()

    class Meta:
        db_table = 'salaries'
        ordering = ['-from_date']
        verbose_name = 'Salary'
        verbose_name_plural = 'Salaries'


class Title(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_num')
    title = models.CharField(max_length=50)
    from_date = models.DateField()
    to_date = models.DateField(blank=True, null=True)

    objects = TemporalQuerySet.as_manager()

    class Meta:
        db_table = 'titles'

staff/forms.py
from django import forms

from .models import Employee, DepartmentManager, Title, Salary


class ChangeManagerForm(forms.Form):
    manager = forms.ModelChoiceField(queryset=Employee.objects.all()[:100])

    def __init__(self, *args, **kwargs):
        self.department = kwargs.pop('department')
        super(ChangeManagerForm, self).__init__(*args, **kwargs)

    def save(self):
        new_manager = self.cleaned_data['manager']

        DepartmentManager.objects.filter(
            department=self.department
        ).set(
            department=self.department,
            employee=new_manager
        )


class ChangeTitleForm(forms.Form):
    position = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop('employee')
        super(ChangeTitleForm, self).__init__(*args, **kwargs)

    def save(self):
        new_title = self.cleaned_data['position']

        Title.objects.filter(
            employee=self.employee,
        ).set(
            employee=self.employee,
            title=new_title
        )


class ChangeSalaryForm(forms.Form):
    salary = forms.IntegerField(max_value=1000000)

    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop('employee')
        super(ChangeSalaryForm, self).__init__(*args, **kwargs)

    def save(self):
        new_salary = self.cleaned_data['salary']

        Salary.objects.filter(
            employee=self.employee,
        ).set(
            employee=self.employee,
            salary=new_salary,
        )

staff/views.py
import json
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import get_object_or_404, render

from material.frontend.views import ModelViewSet, ListModelView

from . import models, forms


@login_required
def change_manager(request, department_pk):
    department = get_object_or_404(models.Department, pk=department_pk)
    form = forms.ChangeManagerForm(department=department, data=request.POST or None)

    if form.is_valid():
        form.save()

    return render(request, 'employees/change_manager.html', {
        'form': form,
        'department': department,
        'model': models.Department
    })


@login_required
def change_salary(request, employee_pk):
    employee = get_object_or_404(models.Employee, pk=employee_pk)
    form = forms.ChangeSalaryForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()

    salaries = employee.salary_set.all().order_by('from_date')
    salary_data = {
        'labels': [salary.from_date.strftime('%Y-%m-%d') for salary in salaries],
        'datasets': [
            {'data': [salary.salary for salary in salaries], 'label': 'Salary History'}
        ]
    }

    return render(request, 'employees/change_salary.html', {
        'form': form,
        'employee': employee,
        'salary_history': json.dumps(salary_data),
        'model': models.Employee
    })


@login_required
def change_title(request, employee_pk):
    employee = get_object_or_404(models.Employee, pk=employee_pk)
    form = forms.ChangeTitleForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()

    return render(request, 'employees/change_title.html', {
        'form': form,
        'employee': employee,
        'model': models.Employee
    })


class DepartmentEmployesListView(ListModelView):
    model = models.Employee
    list_display = ('emp_no', 'first_name', 'last_name', 'current_salary')
    template_name = 'employees/department_employees.html'

    def get_queryset(self):
        today = timezone.now().date()
        department = get_object_or_404(models.Department, pk=self.kwargs['department_pk'])
        queryset = super(DepartmentEmployesListView, self).get_queryset()

        return queryset.filter(
            deptemp__department=department,
            deptemp__from_date__lte=today,
            deptemp__to_date__gt=today
        )

    def get_context_data(self, **kwargs):
        department = get_object_or_404(models.Department, pk=self.kwargs['department_pk'])
        return super(DepartmentEmployesListView, self).get_context_data(
            department=department, **kwargs)


class EmployeeViewSet(ModelViewSet):
    model = models.Employee
    list_display = ('emp_no', 'first_name', 'last_name', 'birth_date', 'current_salary')

    change_salary_view = [
        r'^(?P<employee_pk>.+)/change_salary/$',
        change_salary,
        '{model_name}_change_salary'
    ]

    change_title_view = [
        r'^(?P<employee_pk>.+)/change_title/$',
        change_title,
        '{model_name}_change_title'
    ]

    def current_salary(self, obj):
        salary = obj.salary_set.current()
        return salary.salary if salary is not None else 0


class DepartmentViewSet(ModelViewSet):
    model = models.Department
    list_display = ('dept_no', 'dept_name', 'manager', 'employees')

    change_manager_view = [
        r'^(?P<department_pk>.+)/change_manager/$',
        change_manager,
        '{model_name}_change_manager'
    ]

    employees_list_view = [
        r'^(?P<department_pk>.+)/employees/$',
        DepartmentEmployesListView.as_view(viewset=EmployeeViewSet()),
        '{model_name}_employees'
    ]

    def manager(self, obj, today=None):
        if today is None:
            today = timezone.now().date()
        manager = obj.deptmanager_set.filter(
            from_date__lte=today,
            to_date__gt=today
        ).first()
        return manager.employee if manager is not None else ''

    def employees(self, obj):
        return obj.deptemp_set.count()

staff/templates/employees/base_module.html
{% extends 'material/frontend/base_module.html' %}

{% block js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
{% endblock %}

staff/templates/employees/change_manager.html
{% extends 'employees/base_module.html' %}
{% load material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url department|frontend_urlname:'list' %}">{{ department|verbose_name_plural|title }}</a>
<a href="{% url department|frontend_urlname:'detail' department.pk %}">{{ department }}</a>
<a class="active">Change Manager</a>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-content">
        {{ form }}
    </div>
</div>
{% endblock %}

staff/templates/employees/change_salary.html
{% extends 'employees/base_module.html' %}
{% load material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url employee|frontend_urlname:'list' %}">{{ employee|verbose_name_plural|title }}</a>
<a href="{% url employee|frontend_urlname:'detail' employee.pk %}">{{ employee }}</a>
<a class="active">Change Salary</a>
{% endblock %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">Salary History</div>
            <canvas id="salaryChart" ></canvas>

            <script type="text/javascript">
              new Chart($("#salaryChart"), {
                type: 'line',
                data: {{ salary_history|safe }},
                options: {
                  scales: {
                    xAxes: [{
                      type: 'time',
                    }]
                  }
                }
              });
            </script>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <form method="POST">
            {% csrf_token %}
            <div class="card-content">
                {% form %}
                {% part form.salary prefix %}<i class="material-icons prefix">attach_money</i>{% endpart %}
                {% endform %}
            </div>
            <div class="card-action right-align">
                <button class=" btn" type="submit">Set new Salary</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

staff/templates/employees/change_title.html
{% extends 'employees/base_module.html' %}
{% load material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url employee|frontend_urlname:'list' %}">{{ employee|verbose_name_plural|title }}</a>
<a href="{% url employee|frontend_urlname:'detail' employee.pk %}">{{ employee }}</a>
<a class="active">Change Title</a>
{% endblock %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <form method="POST">
            {% csrf_token %}
            <div class="card-content">
                <div class="card-title">Positions</div>
                <table>
                    <thead>
                        <tr>
                            <td>Position</td>
                            <td>Since</td>
                            <td>To</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for title in employee.title_set.all %}
                        <tr>
                            <td>{{ title.title }}</td>
                            <td>{{ title.from_date }}</td>
                            <td>{{ title.to_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {{ form }}
            </div>
            <div class="card-action right-align">
                <button type="submit" class="btn">Change</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

staff/templates/employees/department_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            {% block card %}
            <div class="form-title">{{ view.model|verbose_name|title }}: {{ object }}</div>
            <table class="table bordered">
                {% for field_name, value in object_data %}
                <tr>
                    <th>{{ field_name }}</th>
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endblock %}
                <tr>
                    <th>Employees</th>
                    <td>
                        <a href="{% url 'employees:department_employees' object.pk %}">{{ object.deptemp_set.count }}</a>
                    </td>
                </tr>
            </table>
        </div>
        <div class="card-action">
            <div class="right-align">
                {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
                {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
            </div>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">Department Managers</div>
            <table>
                <thead>
                    <tr>
                        <td>Manager</td>
                        <td>Since</td>
                    </tr>
                </thead>
                <tbody>
                    {% for manager in object.deptmanager_set.all %}
                    <tr>
                        <td>{{ manager.employee }}</td>
                        <td>{{ manager.from_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:department_change_manager' object.pk %}" class="btn disabled">Change</a>
        </div>
    </div>
</div>
{% endblock %}

staff/templates/employees/department_employees.html
{% extends 'material/frontend/views/list.html' %}
{% load material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url department|frontend_urlname:'list' %}">{{ department|verbose_name_plural|title }}</a>
<a href="{% url department|frontend_urlname:'detail' department.pk %}">{{ department }}</a>
<a class="active">Employees</a>
{% endblock %}

staff/templates/employees/employee_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend humanize %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            {% block card %}
            <div class="form-title">{{ view.model|verbose_name|title }}: {{ object }}</div>
            <table class="table bordered">
                {% for field_name, value in object_data %}
                <tr>
                    <th>{{ field_name }}</th>
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endblock %}
            </table>
        </div>
        <div class="card-action">
            <div class="right-align">
                {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
                {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="card-title">Positions</div>
            <table>
                <thead>
                    <tr>
                        <td>Position</td>
                        <td>Since</td>
                        <td>To</td>
                    </tr>
                </thead>
                <tbody>
                    {% for title in object.title_set.all|slice:":10" %}
                    <tr>
                        <td>{{ title.title }}</td>
                        <td>{{ title.from_date }}</td>
                        <td>{{ title.to_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:employee_change_title' object.pk %}" class="btn">Change</a>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="card-title">Departments</div>
            <table>
                <thead>
                    <tr>
                        <td>Department</td>
                        <td>Since</td>
                        <td>To</td>
                    </tr>
                </thead>
                <tbody>
                    {% for dept in object.deptemp_set.all|slice:":10" %}
                    <tr>
                        <td>{{ dept.department }}</td>
                        <td>{{ dept.from_date }}</td>
                        <td>{{ dept.to_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">Salary</div>
            <table>
                <thead>
                    <tr>
                        <td>Salary</td>
                        <td>Since</td>
                    </tr>
                </thead>
                <tbody>
                    {% for salary in object.salary_set.all|slice:":10" %}
                    <tr>
                        <td>${{ salary.salary|intcomma }}</td>
                        <td>{{ salary.from_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:employee_change_salary' object.pk %}" class="btn">Change</a>
        </div>
    </div>
</div>
{% endblock %}

staff/templates/employees/menu.html
<ul>
    <li><a href="{% url 'employees:department_list' %}">Departments</a></li>
    <li><a href="{% url 'employees:employee_list' %}">Employees</a></li>
</ul>