base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^proceed_ticket/(?P<ticket_id>\d+)/(?P<next_state_id>\d+)/$',
        views.proceed_ticket, name='proceed_ticket')
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

danadams_shop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from raw_materials_dept.admin import admin_site

urlpatterns = [
    url(r'^raw_dept_admin/', admin_site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'', include('inventory.urls', namespace='inventory')),
    url(r'^raw_materials_dept/', include('raw_materials_dept.urls', namespace='raw_materials_dept')),
    url(r'^base/', include('base.urls', namespace='base')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.conf.urls import url

from inventory import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^products/$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]
from django import apps

orders/urls.py
from django.conf.urls import url
from . import views
# Your urlpatterns here
urlpatterns = [
    url(r'^ord/$', views.OrderList.as_view(), name="order_list"),
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf'),
    url(r'^payment/$', views.payment, name='payment'),
]

orders/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from inventory.models import Product
from django.contrib.auth.models import User
import datetime
from django.conf import settings
# Create your models here.


class OrderManager(models.Manager):
    def get_queryset(self):
        return super(OrderManager, self).get_queryset().filter(id='id', ordered=True)


class PaymentMethod(models.Model):
    """
    Represents payment methods for order
    """
    # Payment methods
    COD = 'CO'
    CHECK = 'CH'
    CREDIT_CARD = 'CC'
    PURCHASE_ORDER = 'PO'
    MOBILE_MONEY = 'MO'
    ALL = ((COD, 'Cash On Delivery'),
           (CHECK, 'Check / Money Order'),
           (CREDIT_CARD, 'Credit Card'),
           (PURCHASE_ORDER, 'Purchase Order'),
           (MOBILE_MONEY, 'Mobile Money'))
    ALL_METHODS = dict(ALL)

    code = models.CharField(primary_key=True, max_length=2, choices=ALL)
    name = models.CharField(max_length=100, unique=True)
    is_active = models.BooleanField(default=True)
    updated_by = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        db_table = 'sales_payment_method'
        verbose_name_plural = 'Payment Methods'

    def __str__(self):
        return '%s: %s' % (self.code, self.name)

    @classmethod
    def get_all(cls):
        """
        Returns list of active/supported payments method
        """
        return list(cls.objects.filter(is_active=True))


class Order(models.Model):
    # Payment statuses
    PAYMENT_PENDING = 'PE'
    PAYMENT_AUTHORIZED = 'AU'
    PAYMENT_PAID = 'PA'
    PAYMENT_PARTIALLY_REFUNDED = 'PR'
    PAYMENT_REFUNDED = 'RE'
    PAYMENT_VOID = 'VO'
    PAYMENT_STATUSES = ((PAYMENT_PENDING, 'Pending'),
                        (PAYMENT_AUTHORIZED, 'Authorized'),
                        (PAYMENT_PAID, 'Paid'),
                        (PAYMENT_PARTIALLY_REFUNDED, 'Partially Refunded'),
                        (PAYMENT_REFUNDED, 'Refunded'),
                        (PAYMENT_VOID, 'Void'))
    vendor = models.CharField(max_length=50)
    fullname = models.CharField(max_length=100)
    email = models.EmailField()
    delivery_address = models.CharField(max_length=200)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$')
    contact_number = models.CharField(validators=[phone_regex], max_length=16)  # validators should be a list
    location = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    ordered = models.BooleanField(default=True)
    order_date = models.DateField(default=datetime.date.today)
    sales_person = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE, null=True,
                                     limit_choices_to={'is_staff': True})
    payment_method = models.ForeignKey(PaymentMethod, db_column='payment_method_code', null=True)
    payment_status = models.CharField(max_length=2, choices=PAYMENT_STATUSES, default=PAYMENT_VOID)
    objects = models.Manager()  # The default manager.
    order_manager = OrderManager()  # Our custom manager.

    class Meta:
        ordering = ('vendor', '-created',)
        permissions = (

        )

    def __str__(self):
        if self.ordered:
            status = self.order_date
        else:
            status = "in progress"
        return 'Order {0} {1} {2}'.format(self.id, self.fullname, status)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    @property
    def item_count(self):
        return self.items.count

    def get_full_address(self):
        return "{0}, {1}".format(self.delivery_address, self.location)

    def get_payment_status(self):
        return next((status[1] for status in self.PAYMENT_STATUSES if status[0] == self.payment_status), None)

"""
    def save(self, *args, **kwargs):
        users = User.objects.filter(groups__name='Sales Person')
        for user in users:
            if self.sales_person == user:
                super(Order, self).save(*args, **kwargs)
"""


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    product = models.ForeignKey(Product, related_name='products')
    quantity = models.IntegerField(default=1)
    price = models.DecimalField('Cost per unit', max_digits=10, decimal_places=2,
                               blank=True, null=True)
    date_arrived = models.DateField(blank=True, null=True)
    serial = models.CharField('Serial number', max_length=45,
                              blank=True, null=True)
    location = models.CharField(max_length=45, blank=True, null=True,
                                help_text="example: -80 freezer, refrigerator, Gilmer 283")

    expiry_years = models.DecimalField('Warranty or Item expiration (y)', max_digits=4,
                                       decimal_places=2, blank=True, null=True)

    reconciled = models.BooleanField(default=True)

    class Meta:
        db_table = "inventory_order_items"

    def get_cost(self):
        if self.price is None:
            return 0
        else:
            return self.price * self.quantity

    def name(self):
        return self.product.name

    def order_date(self):
        return self.order.order_date

    def __str__(self):
        return '{0} {1} {2}'.format(self.id, self.product.name, self.order.order_date)


def vendor_url(self):
    try:
        return self.vendor.lookup_url % self.catalog
    except (AttributeError, TypeError):
        return None


def mfg_url(self):
    try:
        return self.manufacturer.lookup_url % self.manufacturer_number
    except (AttributeError, TypeError):
        return None

orders/forms.py
from django import forms
from .models import Order
# from suit.widgets import EnclosedInput


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['vendor', 'fullname', 'email', 'delivery_address', 'contact_number',
                  'location']

        widgets = {
            # By icons

        }

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.http import HttpResponse
from django.conf import settings
from django.template.loader import render_to_string
import weasyprint
from .models import Order, OrderItem
from .forms import OrderForm
from .tasks import order_created
from cart.cart import Cart
from django.views.generic import ListView


def payment(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/order/payment.html', {'order_id': order_id,
                                                         'order': order})

class OrderList(ListView):
    model = Order
    context_object_name = 'orders'

     #display only orders assigned to the logged in user
    def get_queryset(self):
        return Order.objects.filter(sales_person=self.request.user)


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # launch asynchronous task
            #order_created.delay(order.id)  # set the order in the session
            request.session['order_id'] = order.id  # redirect to the payment
            return redirect(reverse('orders:payment'))
    else:
        form = OrderForm()
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/orders/order/detail.html', {'order': order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + '/css/pdf.css')])
    return response

orders/templates/orders/order/add.html
{% extends "inventory/orders/../../../../inventory/templates/inventory/base2.html" %}
{% block title %}Checkout{% endblock %}
{% block container %}
    <h1 class="checkout">Checkout</h1>
    <div class="order-info">
        <h3>Your Order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: {{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Place order">
    </form>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "inventory/base.html" %}
{% block title %}Checkout{% endblock %}
{% block otherLinks %}{% endblock %}
{% block container %}
    <div class="container">
         <div class="row">
        <div class="col-sm-12">
            <h1 class="checkout">Checkout</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <form action="." method="post" class="order-form">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Proceed to Payment">
            </form>
            </div>
        <div class="col-sm-6">
            <div class="order-info">
        <h3>Your Order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>GH₵{{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: GH₵{{ cart.get_total_price }}</p>
    </div>
        </div>

    <div class="row">
        <div class="col-sm-12">

        </div>
    </div>
        </div>
    </div>




{% endblock %}

orders/templates/orders/order/created.html
{% extends "inventory/base3.html" %}
{% block title %}
    Thank you
{% endblock %}
{% block container %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock %}

orders/templates/orders/order/payment.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Payment</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Payment Form Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
            function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="{% static "css/payment.css" %}" rel="stylesheet" type="text/css" media="all" />
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "bootstrap2/css/bootstrap.css" %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static "bootstrap2/css/memenu.css" %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static "bootstrap2/css/style.css" %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static "bootstrap2/css/style1.css" %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static "bootstrap2/css/style3.css" %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css " %}" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
</head>
<body>

    <div id="main_body_wrap" class="main_wrap">
                <div class="main_body_wrap_inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="header">
                                    <div class="header-top1">
            <div class="container">
                <div class="col-sm-3">
                    <div class="top-left">

                </div>
                </div>
                <div class="col-sm-9">
                    <div class="top-right">
                    <ul>
                        <li><a href="{% url "orders:order_create" %}">Checkout</a> </li>
                        <li><a href="#">Login</a> </li>
                        <li><a href="#">Create Account</a> </li>
                        <li>
                            <div class="cart box_1">
                                <!--
                                <a href="javascript:;" class="simpleCart_empty">Empty Cart</a>
						<a href="checkout.html">
						        -->
							 <div class="total">
                                {% with total_items=cart|length %}
                                    {% if cart|length > 0 %}
                                        <a href="{% url "cart:cart_detail" %}">
                                            ${{ cart.get_total_price }}
                                            ({{ total_items }} item{{ total_items|pluralize }}),
                                        </a>
                                        {% else %}
                                            empty cart
                                    {% endif %}
                                {% endwith %}
								<img src="{% static "img/cart-1.png" %}" alt="" />
                                </div>
                                </div>
                        </li>
                        </ul>

                        </div>
                </div>

                </div>
            </div>
        <div class="header-bottom1">

                <div class="container">
                        <div class="col-sm-9">
                            <div id="s5_header_wrap">
                                <img alt="logo" src="{% static "bootstrap2/images/danpong.png" %}"
                                     href="{% url "inventory:product_list" %}"/>

				            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="search-bar1">
					            <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					            <input type="submit" value="">
                            </div>
                        </div>

                    </div>
                    <div class="logo-nav">
                        <div class="col-sm-5">
                            <!--
                            <div class="logo-nav-left">
                                <h1><a href="{#% url "inventory:product_list" %#}">Danpong Group<span>Ghana's best online shop</span></a> </h1>
                            </div> -->
                        </div>
                        <div class="col-sm-4">
                            <div class="logo-nav-left">
				        <div class="top-nav navbar-right">

				</div>


			</div>
                </div>

                <div class="clearfix"> </div>
            </div>
            </div>
        </div>
            </div>
        </div>

    </div>

<!--banner-starts-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="bnr" id="home">
		<div id="top" class="callbacks_container1">
			<ul class="rslides" id="slider4">
                <li>
					<img src="{#% static "img/dp11.jpg" %#}" height="100" alt=""/>
				</li>
			</ul>



		</div>
		<div class="clearfix"> </div>
	</div>

    <!--banner ends-->
    <!--Slider-Starts-Here-->

			<!--End-slider-script-->
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
               <div class="main">
        <div class="payment_header">
            <h1>Payment </h1>
        </div>

		<div class="content">

			<script src="{% static "js/easyResponsiveTabs.js" %}" type="text/javascript"></script>
					<script type="text/javascript">
						$(document).ready(function () {
							$('#horizontalTab').easyResponsiveTabs({
								type: 'default', //Types: default, vertical, accordion
								width: 'auto', //auto or any width like 600px
								fit: true   // 100% fit in a container
							});
						});

					</script>
						<div class="sap_tabs">
							<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
								<div class="pay-tabs">
									<h2>Select Payment Method</h2>
									  <ul class="resp-tabs-list">
										  <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span><label class="pic1"></label>Credit Card</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span><label class="pic3"></label>Bank Deposit</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-2" role="tab"><span><label class="pic4"></label>MTN Mobile Money</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-3" role="tab"><span><label class="pic2"></label>Cash on Delivery</span></li>
										  <div class="clear"></div>
									  </ul>
								</div>
								<div class="resp-tabs-container">
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
										<div class="payment-info">
											<h3>Personal Information</h3>
											<form>
												<div class="tab-for">
													<h5>EMAIL ADDRESS</h5>
														<input type="text" value="">
													<h5>FIRST NAME</h5>
														<input type="text" value="">
												</div>
											</form>
											<h3 class="pay-title">Credit Card Info</h3>
											<form>
												<div class="tab-for">
													<h5>NAME ON CARD</h5>
														<input type="text" value="">
													<h5>CARD NUMBER</h5>
														<input class="pay-logo" type="text" value="0000-0000-0000-0000" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '0000-0000-0000-0000';}" required="">
												</div>
												<div class="transaction">
													<div class="tab-form-left user-form">
														<h5>EXPIRATION</h5>
															<ul>
																<li>
																	<input type="number" class="text_box" type="text" value="6" min="1" />
																</li>
																<li>
																	<input type="number" class="text_box" type="text" value="1988" min="1" />
																</li>

															</ul>
													</div>
													<div class="tab-form-right user-form-rt">
														<h5>CVV NUMBER</h5>
														<input type="text" value="xxxx" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'xxxx';}" required="">
													</div>
													<div class="clear"></div>
												</div>
												<input type="submit" value="SUBMIT">
											</form>
											<div class="single-bottom">
													<ul>
														<li>
															<input type="checkbox"  id="brand" value="">
															<label for="brand"><span></span>By checking this box, I agree to the Terms & Conditions & Privacy Policy.</label>
														</li>
													</ul>
											</div>
										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-1">
										<div class="payment-info">
											<h3>Bank Deposit</h3>
                                                <ul class="payment_details">

                                                        <li>COMPLETE YOUR ORDER FIRST AND THEN MAKE A BANK DEPOSIT/TRANSFER TO :</li>
                                                        <li>Account Name:       Danpong Pharmaceuticals LTD</li>
                                                        <li>Account Number:     XXXXXXXXXXXXXXXX</li>
                                                        <li>Bank:               GHANA COMMERCIAL BANK</li>

                                                        <li>ENTER YOUR ORDER NUMBER AND FULL NAME IN <em>COMMENTS/REMARKS SECTION</em> WHILE MAKING THE TRANSFER/DEPOSIT</li>
                                                        <li><strong>Order will be cancelled if the amount is not received in the above Account within 2 business days.</strong></li>

                                                </ul>
											<a href="#">Continue</a>
										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-2">
										<div class="payment-info">
											<h3>MTN Mobile Money Info</h3>
                                            <ul class="payment_details">
                                                <li>MAKE PAYMENTS FROM YOUR MOBILE MONEY ACCOUNT USING THE DETAILS BELOW: </li>
                                                <li>Account Number:     024-XXX-XXXX</li>
                                                <li>ENTER YOUR ORDER NUMBER IN THE<em>REFERENCE SECTION</em> WHILE MAKING THE TRANSFER/DEPOSIT</li>
                                                <li><strong>Order will be cancelled if the amount is not received in the above Account within 2 business days.</strong></li>
                                            </ul>
                                            <a href="#">Continue</a>
										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-3">
										<div class="payment-info">

											<h3 class="pay-title">Cash On Delivery Info</h3>

                                            <ul class="payment_details">
                                                <li>PAY YOUR CASH ON DELIVERY OF GOODS</li>
                                                <li>RECEIPTS WOULD BE DELIVERED ON PAYMENT</li>

                                            </ul>
                                            <a href="#">Continue</a>

                                            <div class="tab-1 resp-tab-content" aria-labelledby="tab_item-1">

									</div>
										</div>
									</div>
								</div>
							</div>
						</div>

		</div>
	</div>
            </div>
        </div>
    </div>
    <div id="content1">
        <div class="container">
            {% block container %}{% endblock %}
        </div>
    </div>
    <!--footer-starts-->
	<div class="footer">
		<div class="container">
            <div class="row">
                <div class="footer-top">
				<div class="col-sm-6 footer-left">

				</div>
            </div>
                    <div class="col-sm-6 footer-right">
					<p>© 2016 Danpong Group. All Rights Reserved | Design by  <strong>Limitless Apps Studios</strong> </p>
				</div>


				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->
                </div>

        </div>
</body>
</html>

orders/templates/orders/order/pdf.html
{% load static %}
<html>
<head>
    <link href="{% static "css/base0.css" %}" rel="stylesheet">
</head>
<body>
    <h1>My Shop</h1>
    <div id="background">
  <p id="bg-text">DANGPONG GROUP</p>
	</div>

	<div id="content">
        <p>
        Invoice nr. {{ order.id }}<br>
        <span class="secondary">{{ order.created|date:"M d, Y" }}</span>
    </p>

    <h3>Bill to</h3>
    <p>
        {{ order.fullname }}<br>
        {{ order.vendor }}
        {{ order.email }}<br>
        {{ order.delivery_address }}<br>
        {{ order.location}}
    </p>

    <h3>Items bought</h3>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Cost</th>
            </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td>{{ item.product.name }}</td>
                <td class="num">GH₵{{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">GH₵{{ item.get_cost }}</td>
            </tr>
        {% endfor %}
            <tr class="total">
                <td colspan="3">Total</td>
                <td class="num">GH₵{{ order.get_total_cost }}</td>
            </tr>
        </tbody>
    </table>

    <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
        {% if order.paid %}Paid{% else %}Pending payment{% endif %}
    </span>
    </div>

</body>
</html>