base/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^proceed_ticket/(?P<ticket_id>\d+)/(?P<next_state_id>\d+)/$',
        views.proceed_ticket, name='proceed_ticket')
]

danadams_shop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from raw_materials_dept.admin import admin_site

urlpatterns = [
    url(r'^raw_dept_admin/', admin_site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'', include('inventory.urls', namespace='inventory')),
    url(r'^raw_materials_dept/', include('raw_materials_dept.urls', namespace='raw_materials_dept')),
    url(r'^base/', include('base.urls', namespace='base')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shipment/urls.py
from viewflow.flow.viewset import FlowViewSet
from .flows import ShipmentFlow

urlpatterns = FlowViewSet(ShipmentFlow).urls

shipment/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from viewflow.models import Process, Task


class Carrier(models.Model):
    DEFAULT = 'Default'

    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)

    def is_default(self):
        return self.name == Carrier.DEFAULT

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Insurance(models.Model):
    company_name = models.CharField(max_length=50)
    cost = models.IntegerField()

    def __str__(self):
        return '{} ${}'.format(self.company_name, self.cost)


class Shipment(models.Model):
    shipment_no = models.CharField(max_length=50)
    carrier = models.ForeignKey(Carrier, null=True, on_delete=models.CASCADE)

    # customer
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()

    # shipment addres
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    zipcode = models.CharField(max_length=10)
    country = models.CharField(max_length=150)
    phone = models.CharField(max_length=50)

    # shipment data
    need_insurance = models.BooleanField(default=False)
    insurance = models.ForeignKey('Insurance', null=True, on_delete=models.CASCADE)

    carrier_quote = models.IntegerField(default=0)
    post_label = models.TextField(blank=True, null=True)

    package_tag = models.CharField(max_length=50)


class ShipmentItem(models.Model):
    shipment = models.ForeignKey(Shipment, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    quantity = models.IntegerField(default=1)


class ShipmentProcess(Process):
    shipment = models.ForeignKey(Shipment, blank=True, null=True, on_delete=models.CASCADE)

    def is_normal_post(self):
        try:
            if self.shipment.carrier:
                return self.shipment.carrier.is_default()
            else:
                return None
        except (Shipment.DoesNotExist, Carrier.DoesNotExist):
            return None

    def need_extra_insurance(self):
        try:
            return self.shipment.need_insurance
        except Shipment.DoesNotExist:
            return None

    class Meta:
        verbose_name_plural = 'Shipment process list'
        permissions = [
            ('can_start_request', 'Can start shipment request'),
            ('can_take_extra_insurance', 'Can take extra insurance'),
            ('can_package_goods', 'Can package goods'),
            ('can_move_package', 'Can move package')
        ]

    def __str__(self):
        return '{0} {1}'.format(self.shipment.shipment_no, self.shipment.carrier)

class ShipmentTask(Task):
    class Meta:
        proxy = True

shipment/forms.py
from django.forms import ModelForm
from django.forms import inlineformset_factory
from .models import Shipment, ShipmentItem


class ShipmentForm(ModelForm):
    items = inlineformset_factory(
        Shipment, ShipmentItem,
        fields=['name', 'quantity'], can_delete=False)

    class Meta:
        model = Shipment
        fields = [
            'shipment_no', 'first_name', 'last_name',
            'email', 'phone', 'address', 'zipcode',
            'city', 'state', 'country'
        ]

shipment/views.py
from django.views import generic
from material import Layout, Fieldset, Row, Span2, Span5, Span7

from viewflow.flow.views import StartFlowMixin, FlowMixin


from .forms import ShipmentForm
from .models import Insurance


class StartView(StartFlowMixin, generic.UpdateView):
    form_class = ShipmentForm

    layout = Layout(
        Row('shipment_no'),
        Fieldset('Customer Details',
                 Row('first_name', 'last_name', 'email'),
                 Row('phone')),
        Fieldset('Address',
                 Row(Span7('address'), Span5('zipcode')),
                 Row(Span5('city'), Span2('state'), Span5('country'))),
        # 'items',
    )

    def get_object(self):
        return self.activation.process.shipment

    def activation_done(self, form):
        shipment = form.save()
        self.activation.process.shipment = shipment
        super(StartView, self).activation_done(form)


class ShipmentView(FlowMixin, generic.UpdateView):
    def get_object(self):
        return self.activation.process.shipment


class InsuranceView(FlowMixin, generic.CreateView):
    model = Insurance
    fields = ['company_name', 'cost']

    def activation_done(self, form):
        shipment = self.activation.process.shipment
        shipment.insurance = self.object
        shipment.save(update_fields=['insurance'])
        self.activation.done()

shipment/templates/shipment/shipment/process_data.html
{% if process.pk %}
{% with process.shipment as shipment %}
<div class="row">
    <div class="card">
        <div class="card-content">
            <div class="card-title black-text">Shipment #{{ shipment.shipment_no }}</div>
            {% if perms.shipment.change_shipment %}
                <a href="{% url 'admin:shipment_shipment_change' shipment.pk %}" class="card-edit no-pjax" target="_blank">(edit)</a>
            {% endif %}
            <table class="table">
                <thead>
                    <th>Item</th>
                    <th>Count</th>
                </thead>
                <tbody>
                    {% for item in shipment.shipmentitem_set.all %}
                    <tr>
                        <td> {{ item.name }} </td>
                        <td> {{ item.quantity }} </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No items in shipment</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="card-title black-text">Address</div>
            {{ shipment.zipcode }}, {{ shipment.country }}, {{ shipment.city }}, {{ shipment.state }}<br/>
            {{ shipment.address }} <br/><br/>
            <strong>Phone:</strong> {{ shipment.phone }}
        </div>
    </div>
    {% if shipment.carrier or shipment.insurance %}
    <div class="card">
        <div class="card-content">
            <div class="card-title black-text">Delivery</div>
            {% if shipment.carrier %}
            <strong>Carrier:</strong> {{ shipment.carrier.name }}
            {% if perms.shipment.change_carrier %}
                <a href="{% url 'admin:shipment_carrier_change' shipment.carrier.pk %}" class="no-pjax" target="_blank">(edit)</a>
            {% endif %}
            <br/>
            {% endif %}
            {% if shipment.insurance %}
            <strong>Insurance:</strong> {{ shipment.insurance.company_name }} {{ shipment.insurance.cost}}
            {% if perms.shipment.change_insurance %}
                <a href="{% url 'admin:shipment_insurance_change' shipment.insurance.pk %}" class="no-pjax" target="_blank">(edit)</a>
            {% endif %}
            <br/>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>
{% endwith %}
{% endif %}